---
abstract: 'Use objects and data structures in your forms'
author:
  - 'Skye Shaw <sshaw AT lucas.cis.temple.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6101, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ParamExpand
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Expand: 0
  Mojolicious: 2.52
resources:
  bugtracker: http://github.com/sshaw/Mojolicious-Plugin-ParamExpand/issues
  homepage: http://github.com/sshaw/Mojolicious-Plugin-ParamExpand
version: 0.01
